-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Musteriler"
(
    "Id" integer,
    "MusteriNo" "char",
    "KanalId" integer,
    PRIMARY KEY ("Id") 
);

CREATE TABLE public."TuzelMusteri"
(
    "MusteriId" integer,
    "Unvan" character varying(50),
    "TcKimlikNo" character varying(10),
    PRIMARY KEY ("MusteriId") 
);

CREATE TABLE public."GercekMusteriler"
(
    "MusteriId" integer,
    "Ad" character varying(50),
    "Soyad" character varying(50),
    "TcKimlikNo" character varying(11),
    PRIMARY KEY ("MusteriId")
);

CREATE TABLE public."Adresler"
(
    "Id" integer,
    "MusteriId" integer,
    "AdresDetay" character varying(250),
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Bilancolar"
(
    "Id" integer,
    "MusteriId" integer,
    "Tarih" date,
    "Tutar" money,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."TicariFaaliyetler"
(
    "Id" integer,
    "GercekMusteriId" integer,
    "BaslangıcTarihi" date,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Kanallar"
(
    "Id" integer,
    "Ad" character varying(50),
    PRIMARY KEY ("Id")
);

ALTER TABLE public."GercekMusteriler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" ("Id")
    NOT VALID;


ALTER TABLE public."TuzelMusteri"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" ("Id")
    NOT VALID;


ALTER TABLE public."Adresler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" ("Id")
    NOT VALID;


ALTER TABLE public."Bilancolar"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" ("Id")
    NOT VALID;


ALTER TABLE public."TicariFaaliyetler"
    ADD FOREIGN KEY ("GercekMusteriId")
    REFERENCES public."GercekMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Kanallar"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Musteriler" ("KanalId")
    NOT VALID;

END;